/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author Dev
 */
public class Bookmarks extends javax.swing.JFrame {

    /**
     * Creates new form openWebpage
     */
    public Bookmarks() {
        initComponents();
        onRun();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        link1 = new javax.swing.JLabel();
        link2 = new javax.swing.JLabel();
        link3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        link1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        link1.setText("freeCodeCamp");
        link1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link1MouseClicked(evt);
            }
        });

        link2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        link2.setText("medium");
        link2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link2MouseClicked(evt);
            }
        });

        link3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        link3.setText("tutorialspoint");
        link3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(link2)
                    .addComponent(link1)
                    .addComponent(link3))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(link1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(link2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(link3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void link1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link1MouseClicked
        try {
            Desktop.getDesktop().browse(new URL("https://www.freecodecamp.org/nhut-git").toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_link1MouseClicked

    private void link2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link2MouseClicked
        try {
            Desktop.getDesktop().browse(new URL("https://medium.freecodecamp.org/").toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_link2MouseClicked

    private void link3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link3MouseClicked
        try {
            Desktop.getDesktop().browse(new URL("https://www.tutorialspoint.com/tutorialslibrary.htm").toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_link3MouseClicked

    public void onRun() {
        link1.setForeground(new java.awt.Color(0, 102, 0));
        link1.setToolTipText("www.freecodecamp.org/nhut-git");
        link2.setForeground(new java.awt.Color(9, 133, 135));
        link2.setToolTipText("medium.freecodecamp.org");
        link3.setForeground(new java.awt.Color(69, 165, 106));
        link3.setToolTipText("www.tutorialspoint.com/tutorialslibrary");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("bookmarks.png")));
        getContentPane().setBackground(new java.awt.Color(248, 246, 238));
        setTitle("Bookmarks");
    }

    public void onStop() {
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookmarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel link1;
    private javax.swing.JLabel link2;
    private javax.swing.JLabel link3;
    // End of variables declaration//GEN-END:variables
}
